sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t front-dm/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true front-dm/docker-react npm run test