sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t front-dm/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true front-dm/docker-react npm run test

# deploy:
#   provider: elasticbeanstalk
#   region: "us-west-2"
#   app: "docker-react"
#   env: "DockerReact-env"
#   bucket_name: "elasticbeanstalk-us-west-2-299501275255"
#   bucket_path: docker
#   on
#     branch: master